-- =====================================================================
-- EverNest 32: Safe-to-spend projects forward and takes the minimum
--
-- getSafeToSpend (lib/db/dashboard.ts) now walks a day-by-day projection
-- to max(35 days, the payday after next) and reports the lowest balance
-- minus a cushion -- see lib/safeToSpendProjection.ts. This migration adds
-- what that needs from the database:
--
--   settings.safe_to_spend_cushion   per-user cushion, dollars. Null
--                                    means "use the suggestion" below;
--                                    0 is a real, allowed choice.
--   suggested_safe_to_spend_cushion() seven days of average daily
--                                    variable spend, to the nearest $25,
--                                    with 60+ days of history; $200 flat
--                                    otherwise. Aggregated here, never in
--                                    JS.
--   estimate_income_amount_low()     the low estimate a projection uses
--                                    for a variable Income schedule.
--   v_upcoming_recurring             four appended columns so the
--                                    projection can step every schedule
--                                    past its next occurrence:
--                                    amount_low, business_day_offset,
--                                    non_business_day_rule,
--                                    occurrences_remaining.
-- =====================================================================

alter table public.settings
  add column if not exists safe_to_spend_cushion numeric(12,2);

alter table public.settings
  drop constraint if exists settings_safe_to_spend_cushion_nonnegative;

alter table public.settings
  add constraint settings_safe_to_spend_cushion_nonnegative
  check (safe_to_spend_cushion is null or safe_to_spend_cushion >= 0)
  not valid;

alter table public.settings
  validate constraint settings_safe_to_spend_cushion_nonnegative;

-- =====================================================================
-- suggested_safe_to_spend_cushion()
--
-- "Variable spend" is every Expense that isn't generated by a schedule
-- (recurringid is null -- those are already in the projection as
-- obligations) and isn't a transfer leg. Averaged over the trailing 90
-- days, or the whole history if shorter -- but only once there are 60
-- days of it; before that the average is too noisy to lean on and the
-- flat $200 applies.
--
-- security invoker: RLS on transactions scopes it to the caller.
-- =====================================================================

create or replace function public.suggested_safe_to_spend_cushion()
returns numeric
language sql
stable
security invoker
set search_path = public
as $$
  with history as (
    select current_date - min(transaction_date) as days
    from transactions
  ),
  span as (
    select least(days, 90) as days
    from history
    where days >= 60
  )
  select coalesce(
    (
      select round(
        coalesce(
          (
            select sum(t.amount)
            from transactions t
            where t.transaction_type = 'Expense'
              and t.recurringid is null
              and t.transfer_group_id is null
              and t.transaction_date > current_date - span.days
              and t.transaction_date <= current_date
          ),
          0
        ) / span.days * 7 / 25
      ) * 25
      from span
    ),
    200
  );
$$;

comment on function public.suggested_safe_to_spend_cushion() is
  'Default safe-to-spend cushion: seven days of average daily non-recurring, non-transfer Expense spend (trailing 90 days, or all history if shorter), rounded to the nearest $25, once there are 60+ days of history; $200 otherwise. settings.safe_to_spend_cushion overrides it when non-null.';

revoke all on function public.suggested_safe_to_spend_cushion() from public, anon;
grant execute on function public.suggested_safe_to_spend_cushion() to authenticated;

-- =====================================================================
-- estimate_income_amount_low(p_recurring_id, p_fallback_amount)
--
-- The low counterpart to estimate_income_amount: the smallest of the last
-- three confirmed Income transactions for the schedule. With fewer than
-- three, the smaller of the stated amount and anything confirmed so far.
-- =====================================================================

create or replace function public.estimate_income_amount_low(p_recurring_id uuid, p_fallback_amount numeric)
returns numeric
language sql
stable
security invoker
set search_path = public
as $$
  select case
    when count(*) >= 3 then min(t.amount)
    else least(p_fallback_amount, coalesce(min(t.amount), p_fallback_amount))
  end
  from (
    select amount
    from transactions
    where recurringid = p_recurring_id and transaction_type = 'Income'
    order by transaction_date desc, created_at desc
    limit 3
  ) t;
$$;

comment on function public.estimate_income_amount_low(uuid, numeric) is
  'Low estimate for a variable-amount Income schedule: min of the last three confirmed Income transactions linked by recurringid, or least(stated amount, anything confirmed) with fewer than three. Read by the safe-to-spend projection, which counts income at its low estimate.';

revoke all on function public.estimate_income_amount_low(uuid, numeric) from public, anon;
grant execute on function public.estimate_income_amount_low(uuid, numeric) to authenticated;

-- =====================================================================
-- v_upcoming_recurring: unchanged from 31_recurring_expense_variability.sql
-- except for four columns appended after requires_confirmation.
--
--   amount_low             null unless this is a variable-amount Income
--                          category schedule; readers treat null as
--                          "same as amount".
--   occurrences_remaining  null when uncapped. Same ledger count the
--                          where-clause guard below already uses.
-- =====================================================================

create or replace view public.v_upcoming_recurring
with (security_invoker = true) as
select
  r.id as recurring_id, r.userid, r.description,
  case
    when not r.amount_is_variable then r.amount
    when r.to_accountid is not null and r.next_amount_confirmed_at is not null then r.next_amount
    when r.to_accountid is not null then greatest(-cb.balance, 0)
    when c.category_type = 'Expense' then public.estimate_expense_amount(r.id, r.amount)
    else public.estimate_income_amount(r.id, r.amount)
  end as amount,
  r.frequency,
  r.next_run_date, r.start_date, r.end_date,
  r.accountid, a.account_name, a.color as account_color,
  r.categoryid, c.category_name, c.icon as category_icon, c.color as category_color,
  (r.next_due_date - current_date) as days_until,
  (r.next_due_date < current_date) as is_overdue,
  r.interval_count, r.occurrence_limit,
  r.to_accountid, ta.account_name as to_account_name,
  c.category_type,
  r.amount_is_variable, r.statement_day, r.next_amount, r.next_amount_confirmed_at,
  (r.amount_is_variable and (r.to_accountid is null or r.next_amount_confirmed_at is null)) as is_estimated_amount,
  r.next_due_date, a.account_type,
  ta.account_type as to_account_type,
  r.date_tolerance_days, r.requires_confirmation,
  case
    when r.amount_is_variable and r.to_accountid is null and c.category_type = 'Income'
      then public.estimate_income_amount_low(r.id, r.amount)
  end as amount_low,
  r.business_day_offset, r.non_business_day_rule,
  case
    when r.occurrence_limit is not null
      then r.occurrence_limit - (select count(*) from transactions t where t.recurringid = r.id)
  end as occurrences_remaining
from recurring_transactions r
join accounts a        on a.id  = r.accountid
left join categories c on c.id  = r.categoryid
left join accounts ta  on ta.id = r.to_accountid
left join public.v_account_balances cb on cb.account_id = r.to_accountid
where r.is_active
  and (r.end_date is null or r.end_date >= current_date)
  and (r.occurrence_limit is null
       or (select count(*) from transactions t where t.recurringid = r.id) < r.occurrence_limit);

grant select on public.v_upcoming_recurring to authenticated;
revoke all on public.v_upcoming_recurring from anon;
